import Head from 'next/head'
import {BsMoonStarsFill} from 'react-icons/bs'
import {AiFillLinkedin, AiFillGithub, AiFillInstagram, AiFillTwitterCircle} from 'react-icons/ai'
import { useState } from 'react'
import logo from '../../public/logo.png'
import full_logo from '../../public/full-logo.png'
import design from '../../public/design.png'
import code from '../../public/code.png'
import Image from 'next/image'

export default function Home() {

  const [darkMode, setDarkMode] = useState(false)
  return (
    <div
      className={darkMode ? "dark": ""}
    >
      <Head>
        <title>Epoupa's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <main className='bg-gradient-to-b from-slate-200 to-slate-100  dark:bg-gradient-to-b dark:from-cyan-900 dark:to-teal-700'>
        <section className='min-h-screen' >
          <nav className='py-10 flex justify-between shadow-md px-10 md:px20 lg:px-20'>
            <div>
              <Image src={logo} width="40" className='rounded-full w-10 h-10'/>
             <h1 className='text-xl font-burtons'>peliah</h1>
            </div>
            <ul className='flex items-center'>
              <li><BsMoonStarsFill className='cursor-pointer text-2xl' onClick={()=>setDarkMode(!darkMode)}/></li>
              <li>
                <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' 
                href='/resume.pdf' download>
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className='px-10 md:px20 lg:px-20'>
            <div className='text-center p-10'>
              <h2 className='text-5xl text-teal-500 font-medium'>Epoupa Pelayah</h2>
              <h3 className='text-2xl py-2'>Software Engineer</h3>
              <p className='text-md py-5 leading-8 text-gray-800'>
                Highly motivated Software Engineer, providing services for programming and Design.
                Join me down below, let's explore!!! 
              </p>
            </div>
            <div className='text-5xl flex justify-center gap-16 py-3 text-gray-700 dark:text-black'>
              <a href='https://www.github.com/peliah'><AiFillGithub /></a>
              <a href='https://www.linkedin.com/in/pelayah-epoupa-12830a198'><AiFillLinkedin/></a>
              <a href='https://www.twitter.com/pelayah_epoupa'><AiFillTwitterCircle/></a>
              <a href='#'><AiFillInstagram/></a>
            </div>
            <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden'>
              <Image src={full_logo} layout="fill" objectFit='cover'/>
            </div>
          </div>
        </section>
        <section className='px-10 md:px20 lg:px-20'>
          <div>
            <h3 className='text-3xl py-1'>Services I Offer</h3>
          </div>
          <div>
            <p className='text-md leading-8 text-gray-800'>
              Since the beginning of my journey as a developer, I've done remote work for <span className='text-teal-500'>agencies</span>
              , consulted for <span className='text-teal-500'>startups</span> and collaborated with talented people to create digital products
              for both business and consumer use.
            </p>
            <p>
              I offer a wide range of services, including programming and teaching.
            </p>
          </div>
          <div className=' md:flex md:justify-evenly'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
            <div className='relative mx-auto w-20 h-20 mt-20 overflow-hidden'>

                <Image src={design} width={100} height={100} /></div>
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
              <p className='py-2'>
                Creating elegent designs suited for your needs following core design theory
              </p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>CorelDraw</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
            <div className='relative mx-auto w-20 h-20 mt-20 overflow-hidden'>

                <Image src={code} width={100} height={100} /></div>
              <h3 className='text-lg font-medium pt-8 pb-2'>Codes</h3>
              <p className='py-2'>
                Creating elegent designs suited for your needs following core design theory
              </p>
              <h4 className='py-4 text-teal-600'>Programming leanguages I use</h4>
              <p className='text-gray-800 py-1'>Java</p>
              <p className='text-gray-800 py-1'>JavaScript</p>
              <p className='text-gray-800 py-1'>Python</p>
            </div>
          </div>
        </section>
        <section>
          <footer className=' bg-gradient-to-r from-cyan-800 to-teal-800 py-16 flex justify-between shadow-sm px-10 md:px20 lg:px-20'>
            <div className='flex justify-between gap-2'>
              <Image src={logo} width="50" height="50" className='rounded-full w-16 h-16'/>
              <h1 className='text-xl font-burtons'>peliaH</h1>
            </div>
            <div>
            <h3 className='font-burtons'>Social</h3>
            <div className='text-4xl flex justify-center gap-16 py-3 text-gray-800 dark:text-black'>
              <a href='https://www.github.com/peliah'><AiFillGithub /></a>
              <a href='https://www.linkedin.com/in/pelayah-epoupa-12830a198'><AiFillLinkedin/></a>
              <a href='https://www.twitter.com/pelayah_epoupa'><AiFillTwitterCircle/></a>
              <a href='#'><AiFillInstagram/></a>
            </div>
            </div>
          </footer>
        </section>
      </main>
    </div>
  )
}
